name: module3_task1
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  module3_task1:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout the repository
        uses: actions/checkout@v3

      - name: setup and Build
        run: |
          cd module3_task1
          ./setup.sh
          make build

      - name: clean up the dist
        run: |
          cd module3_task1
          make clean
