name: module3_task1
on:
  schedule:
    - cron: '30 5 * * *'
  push:
    branches:
      - main

jobs:
  module3_task1:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout the repository
        uses: actions/checkout@v3
      - name: Setup environment
        run:
          ./module3_task1/setup.sh

      - name: Build
        run: |
          cd module3_task1
          make build

      - name: Create post
        env:
          POST_NAME: my-post
          POST_TITLE: My Post
        run: |
          cd module3_task1
          make post

      - name: clean up the dist
        run: |
          cd module3_task1
          make clean
