---
name: module3_task0

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Position in correct directory and execute make help
        run: |
          git clone
            https://github.com/MurdoNicolai/holbertonschool-validation.git
          cd module3_task0
          make help
