name: module3_task0
on:
  schedule:
    - cron: '30 5 * * *'
  push:
    branches:
      - main

jobs:
  module3_task0:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v3
      - name: create new workflow
        run: |
          git clone https://github.com/luciel53/holbertonschool-validation.git
          cd module3_task0
          make help
