---
name: module3_task4
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    tags:
      - '1.0.0'
    branches:
      - main
  pull_request:
jobs:
  module3_task4:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout the repository
        uses: actions/checkout@v3

      - name: create new workflow
        run: >
          git clone
          "https://github.com/MurdoNicolai/holbertonschool-validation.git"

      - name: setup and Build
        run: |
          cd module3_task4
          chmod +x setup.sh
          sudo -E ./setup.sh
          make package
          make lint
          make unit-tests


      - name: Build
        run: echo ${{ github.sha }} > Release.txt

      - name: 1.0.0
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/1.0.0')
        with:
          files: |
            awesome-website.zip
          body:
            cat DEPLOY.md
